# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.0.3
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/python:3.10.5

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      # - python/install-packages:
      #     pkg-manager: pip
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: "Tests"
          command: |
            python --version
            pip install pytest
            ls
            cd example-py-pytest
            python -m pytest --junitxml=results/test-results.xml
      - run:
          name: Install Testmo CLI
          command: sudo npm install -g @testmo/testmo-cli
      - run:
          name: Submit test results to Testmo
          command: |
            TESTMO_TOKEN="testmo_api_eyJpdiI6IkhnSHlaMEE2L2xEc0h0eUNZZnJ4T1E9PSIsInZhbHVlIjoiTFc2UEZFMVBieGpqdHNZY1ZaQ09jWXdNN2hVVmc0WU1VQTNZRjdIdzluRT0iLCJtYWMiOiJhOGY4YWNkM2RlY2I2Y2NiMjg4ZTQ4ZWJmYTBlNzBjZjhjNGNmNzBkZjFlMDJiMGY4NmZiMjdmN2RkMTc4Njk4IiwidGFnIjoiIn0="
            TESTMO_URL="https://adam-walaszczyk.testmo.net/"
            testmo automation:run:submit \
            --token $TESTMO_TOKEN \
            --instance $TESTMO_URL \
            --project-id 1 \
            --source "regression" \
            --name "CircleCI execution" \
            --results results/test-results.xml

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
